services:
  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "55433:5432"
    command: ["postgres", "-c", "listen_addresses=*"]
    volumes:
      - pgdata:/var/lib/postgresql/data


  mongo:
    image: mongo:7
    container_name: mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    volumes:
      - mongo_data:/data/db


  neo4j:
    image: neo4j:5-community
    container_name: topjodel_neo4j
    restart: unless-stopped
    ports:
      - "7474:7474"   # HTTP
      - "7687:7687"   # Bolt
    environment:
      NEO4J_AUTH: ${NEO4J_AUTH}
      NEO4J_server_memory_pagecache_size: 512M
      NEO4J_server_memory_heap_initial__size: 512M
      NEO4J_server_memory_heap_max__size: 512M
      # Uncomment to allow APOC if you later add the APOC plugin
      # NEO4JLABS_PLUGINS: '["apoc"]'
      # NEO4J_dbms_security_procedures_unrestricted: "apoc.*"
    volumes:
      - neo4jdata:/data

volumes:
  pgdata:
  mongo_data:
  neo4jdata:
